### PR TITLE
Test: matched routes cannot resolve once superseded

### PR DESCRIPTION
**Pull request by barneycarroll**
In this contrived simulation of a race conflict, route A is matched but doesn't resolve. The route is then set to B, and during B's onmatch window, route A attempts (and fails) to resolve.

### CODE REVIEW

**Comment by pygy** [comment]
@barneycarroll my commit history is becoming a tangled mess, I'd like to rebase but it would erase your contributions from history, so I'll start afresh.

Could you consolidate your tests into a single PR against the `router-WIP` branch of this repo?

Route resolver have `onmatch(resolve, args, path, route)` and `render(vnode)` as methods (and use Leo's original implementation).

Thanks for the help on this :-), and sorry for the inconvenience...

**Comment by pygy** [comment]
@lhorie moved the HEAD forward. Rebasing, and waiting for his input since he closed https://github.com/lhorie/mithril.js/pull/1262.

**Comment by barneycarroll** [comment]
Sorry @pygy been busy. I'll come back to this later this morning.

**Comment by pygy** [comment]
No problem, and no hurry, I'd wait for @lhorie's opinion before moving forward.

**Pull request closed without merging**
